# https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/#deploy-with-wrangler

name: Build and deploy to Cloudflare Pages

on:
  workflow_dispatch:
    inputs:
      commit:
        description: The specific commit SHA or branch name to build from (e.g., main or a feature branch)
        required: true
        default: main

jobs:
  deploy:
    name: Build and deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit }}

      - name: Build the Docker image
        run: >
          docker build
          --tag kokoro-web:latest
          --file docker/Dockerfile.dev .

      - name: Build and deploy
        run: >
          docker run --rm -v $PWD:/app kokoro-web:latest /bin/bash -c "
            cd /app &&
            npm install &&
            npm run build:static &&
            CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}
            npx wrangler pages deploy build --project-name=voice-generator
          "
